---
name: "Docker image build"
on:
  push:
    - main

jobs:
  dockerimage-build:
    runs-on: ubuntu-latest


    steps:
      - name: checkout
        uses: actions/checkout@4

      - name: build
        run: docker build -t subin166/myapplication:latest ./my-node-app
      - name: docker login
        uses: docker/login-checkout@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: push images
        run: docker push subin166/myapplication:latest
